name = "atlassian-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "atlassian-mcp-server"

[env.staging]
name = "atlassian-mcp-server-staging"

# Environment variables (will be set via secrets)
[vars]
# These will be set as secrets via wrangler secret put
# ATLASSIAN_EMAIL = ""
# ATLASSIAN_API_TOKEN = ""
# ATLASSIAN_JIRA_URL = ""
# ATLASSIAN_CONFLUENCE_URL = ""